# Generated by Django 4.2.6 on 2023-10-31 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('students_courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students_Courses',
            new_name='StudentCourse',
        ),
    ]
