# Generated by Django 4.2.6 on 2023-11-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0002_rename_students_courses_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
