# Generated by Django 4.2.6 on 2023-10-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_status'),
        ('students_courses', '0002_rename_students_courses_studentcourse'),
        ('accounts', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='my_course',
            field=models.ManyToManyField(related_name='students', through='students_courses.StudentCourse', to='courses.course'),
        ),
    ]
