# Generated by Django 4.2.6 on 2023-10-31 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0002_rename_students_courses_studentcourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='my_courses', through='students_courses.StudentCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
